name: "fastapi-chat"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI:?}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME:-fastapi-chat}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL:?}

      DOMAIN_NAME: ${DOMAIN_NAME:?}

      AUTHORIZATION_SERVER_URL: ${AUTHORIZATION_SERVER_URL:?}
      CLIENT_ID: ${CLIENT_ID:?}
